#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/columnar
#
# IDENTIFICATION
#    src/backend/access/columnar/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/columnar
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = columnar.o colpage.o colinsert.o

include $(top_srcdir)/src/backend/common.mk
