#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mvstats
#
# IDENTIFICATION
#    src/backend/utils/mvstats/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/mvstats
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = common.o dependencies.o histogram.o mcv.o

include $(top_srcdir)/src/backend/common.mk
