CREATE TABLE t1 (a INT, b INT, c INT);
CREATE TABLE t2 (d INT, e INT, f INT);
CREATE TABLE t3 (g INT, h INT, i INT);

INSERT INTO t1 SELECT i, i, mod(i * 7121, 1000) FROM generate_series(1,10000) s(i);
INSERT INTO t2 SELECT i, i, mod(i * 5443, 1000) FROM generate_series(1,10000) s(i);
INSERT INTO t3 SELECT i, i, mod(i * 5441, 1000) FROM generate_series(1,10000) s(i);

VACUUM ANALYZE t1;
VACUUM ANALYZE t2;
VACUUM ANALYZE t3;

LOAD 'gjoin';
SET gjoin.enabled = true;

EXPLAIN (VERBOSE, COSTS OFF, BUFFERS OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g);

EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g) LIMIT 100;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g) LIMIT 200;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g) LIMIT 500;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g) LIMIT 1000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g) LIMIT 5000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g) LIMIT 10000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d) JOIN t3 ON (t1.b = t3.g);

EXPLAIN (VERBOSE, COSTS OFF, BUFFERS OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5);

EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5) LIMIT 100;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5) LIMIT 200;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5) LIMIT 500;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5) LIMIT 1000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5) LIMIT 5000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5) LIMIT 10000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND mod(t1.c + t2.f, 10) < 5) JOIN t3 ON (t1.b = t3.g AND mod(t1.c + t3.i, 10) < 5);

EXPLAIN (VERBOSE, COSTS OFF, BUFFERS OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i);

EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i) LIMIT 100;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i) LIMIT 200;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i) LIMIT 500;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i) LIMIT 1000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i) LIMIT 5000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i) LIMIT 10000;
EXPLAIN (VERBOSE, ANALYZE, COSTS OFF, TIMING OFF, BUFFERS OFF, SUMMARY OFF) SELECT * FROM t1 JOIN t2 ON (t1.a = t2.d AND t1.c < t2.f) JOIN t3 ON (t1.b = t3.g AND t1.c < t3.i);

DROP TABLE t1;
DROP TABLE t2;
DROP TABLE t3;
