#!/bin/bash

OUTDIR=$(date +%Y%m%d-%H%M%S)
mkdir $OUTDIR

for s in perf_validate_int_int perf_validate_int_numeric perf_validate_numeric_int perf_validate_numeric_numeric perf_validation_improvements perf_validation_fat_skinny perf_validation_fat_skinny_backwards; do
	./run_perf_validation $OUTDIR $s.sql > $OUTDIR/$s.txt 2>&1
done

./run_multirange_perf_validation $OUTDIR > $OUTDIR/run_multirange_perf_validation.txt 2>&1

for rows in 100000 1000000 10000000 25000000; do

	export PGPORT=6001
	./run.sh $OUTDIR master $rows > $OUTDIR/master-$rows.log 2>&1

	export PGPORT=6002
	./run.sh $OUTDIR patched $rows > $OUTDIR/patched-$rows.log 2>&1

done
