#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for colstore
#
# IDENTIFICATION
#    src/backend/colstore/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/colstore
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS= colstore_dummy.o

include $(top_srcdir)/src/backend/common.mk
