#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mmgr
#
# IDENTIFICATION
#    src/backend/utils/mmgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/mmgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = aset.o genslab.o mcxt.o portalmem.o slab.o

include $(top_srcdir)/src/backend/common.mk
