set enable_seqscan = off;
set max_parallel_workers_per_gather=0;
\getenv abs_srcdir PG_ABS_SRCDIR

-- Set log_btree_verbosity to 1 without depending on having that patch
-- applied (HACK, just sets commit_siblings instead when we don't have that
-- patch available):
select set_config((select coalesce((select name from pg_settings where name = 'log_btree_verbosity'), 'commit_siblings')), '1', false);
set client_min_messages=debug1;

select count(*) from skiptest where b=1;

SELECT * FROM test_one_int_int WHERE id2 = 1;
SELECT * FROM test_one_int_int WHERE id2 = 501;
SELECT * FROM test_one_int_int WHERE id2 = 900;
SELECT * FROM test_one_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_one_int_int_sequential WHERE id2 = 1;
SELECT * FROM test_one_int_int_sequential WHERE id2 = 501;
SELECT * FROM test_one_int_int_sequential WHERE id2 = 900;
SELECT * FROM test_one_int_int_sequential WHERE id2 IN (0, 1, 900);
SELECT * FROM test_five_int_int WHERE id2 = 1;
SELECT * FROM test_five_int_int WHERE id2 = 501;
SELECT * FROM test_five_int_int WHERE id2 = 900;
SELECT * FROM test_five_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_ten_int_int WHERE id2 = 1;
SELECT * FROM test_ten_int_int WHERE id2 = 501;
SELECT * FROM test_ten_int_int WHERE id2 = 900;
SELECT * FROM test_ten_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_fifteen_int_int WHERE id2 = 1;
SELECT * FROM test_fifteen_int_int WHERE id2 = 501;
SELECT * FROM test_fifteen_int_int WHERE id2 = 900;
SELECT * FROM test_fifteen_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_seventeen_int_int WHERE id2 = 1;
SELECT * FROM test_seventeen_int_int WHERE id2 = 501;
SELECT * FROM test_seventeen_int_int WHERE id2 = 900;
SELECT * FROM test_seventeen_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_twenty_int_int WHERE id2 = 1;
SELECT * FROM test_twenty_int_int WHERE id2 = 501;
SELECT * FROM test_twenty_int_int WHERE id2 = 900;
SELECT * FROM test_twenty_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_twentyfive_int_int WHERE id2 = 1;
SELECT * FROM test_twentyfive_int_int WHERE id2 = 501;
SELECT * FROM test_twentyfive_int_int WHERE id2 = 900;
SELECT * FROM test_twentyfive_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_fifty_int_int WHERE id2 = 1;
SELECT * FROM test_fifty_int_int WHERE id2 = 501;
SELECT * FROM test_fifty_int_int WHERE id2 = 900;
SELECT * FROM test_fifty_int_int WHERE id2 IN (0, 1, 900);
SELECT * FROM test_five_hundred_int_int WHERE id2 = 1;
SELECT * FROM test_five_hundred_int_int WHERE id2 = 501;
SELECT * FROM test_five_hundred_int_int WHERE id2 = 900;
SELECT * FROM test_five_hundred_int_int WHERE id2 IN (0, 1, 900);

select * from test_multirange where a = 42 and c = 1;
select * from test_multirange where a = 42 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange where a between 0 and 42 and b between 0 and 1_000_000 and c = 1;
select * from test_multirange where a between 0 and 42 and b between 0 and 1_000_000 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange where a between 0 and 42 and c = 1;
select * from test_multirange where a between 0 and 42 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange where b between 0 and 1_000_000 and c = 1;
select * from test_multirange where b between 0 and 1_000_000 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange where b between 0 and 1 and c = 1;
select * from test_multirange where b between 0 and 1 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a = 42 and c = 1;
select * from test_multirange_allhighcardinality where a = 42 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a between 0 and 42 and b between 0 and 1_000_000 and c = 1;
select * from test_multirange_allhighcardinality where a between 0 and 42 and b between 0 and 1_000_000 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a between 0 and 42 and c = 1;
select * from test_multirange_allhighcardinality where a between 0 and 42 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a between 0 and 42;
select * from test_multirange_allhighcardinality where a between 0 and 42 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a between 0 and 42 and b = 555;
select * from test_multirange_allhighcardinality where a between 0 and 42 and b = 555 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a between 0 and 1_000_000 and b = 555;
select * from test_multirange_allhighcardinality where a between 0 and 1_000_000 and b = 555 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where a between 0 and 1_000_000 and c = 555;
select * from test_multirange_allhighcardinality where a between 0 and 1_000_000 and c = 555 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where b between 0 and 1_000_000 and c = 1;
select * from test_multirange_allhighcardinality where b between 0 and 1_000_000 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where b between 0 and 1 and c = 1;
select * from test_multirange_allhighcardinality where b between 0 and 1 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_allhighcardinality where b between 0 and 1 and c between 0 and 1;
select * from test_multirange_allhighcardinality where b between 0 and 1 and c between 0 and 1 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a = 42 and c = 1;
select * from test_multirange_medcard where a = 42 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a between 0 and 42 and b between 0 and 1_000_000 and c = 1;
select * from test_multirange_medcard where a between 0 and 42 and b between 0 and 1_000_000 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a between 0 and 42 and c = 1;
select * from test_multirange_medcard where a between 0 and 42 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a between 0 and 42;
select * from test_multirange_medcard where a between 0 and 42 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a between 0 and 42 and b = 555;
select * from test_multirange_medcard where a between 0 and 42 and b = 555 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a between 0 and 1_000_000 and b = 555;
select * from test_multirange_medcard where a between 0 and 1_000_000 and b = 555 order by a desc, b desc, c desc;
select * from test_multirange_medcard where a between 0 and 1_000_000 and c = 555;
select * from test_multirange_medcard where a between 0 and 1_000_000 and c = 555 order by a desc, b desc, c desc;
select * from test_multirange_medcard where b between 0 and 1_000_000 and c = 1;
select * from test_multirange_medcard where b between 0 and 1_000_000 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_medcard where b between 0 and 1 and c = 1;
select * from test_multirange_medcard where b between 0 and 1 and c = 1 order by a desc, b desc, c desc;
select * from test_multirange_medcard where b between 0 and 1 and c between 0 and 1;
select * from test_multirange_medcard where b between 0 and 1 and c between 0 and 1 order by a desc, b desc, c desc;
